### ISSUE TITLE
Missing tiles

### ISSUE THREAD

**Issue by alexhorner** [twooot/legacyrp-admin-panel-sockets#1]
Hi there,

The tiles archive you have linked to on the readme does not appear to exist in the latest repo,

Using the linux binary

**Comment by coalaura** [comment]
Oh yeah, i moved the whole tile image provider to its own server which has cloudflare for caching in front of it. Just forgot to remove it from the README. I'll update it asap

**Comment by coalaura** [comment]
@alexhorner I've updated the README with up-to-date installation instructions
